### PR TITLE
fix: Introduce registration page and routing

### LINKED ISSUE #81: Introduce registration page
## Description
We need a registration page so that users can add new registration when they want to sign up.

### PR DESCRIPTION
**Pull request by MgenGlder**
Closes https://github.com/dearborn-coding-club/website-base-frontend/issues/81

## Summary
- Adds new `/registration` routing, page, and link in hamburger menu.

## Context
We have a login page now but we need a registration page so we show that we're doing things.

### CODE REVIEW

File: src/hooks/registerOnSubmit.tsx [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+        body: JSON.stringify({username: username, password: password})
+    })
+    .then(res => {
+        if(res.status !== 200) {
+            throw new Error();
+        }
+        return res.json()
+    })
+    .then(res => {
+        if (res.status !== 200) {
```
Comment (gonzalolanderos) [inline src/hooks/registerOnSubmit.tsx]: Shouldn't it be `==200`?

Comment (MgenGlder) [reply src/hooks/registerOnSubmit.tsx]: Thanks! Fixed

**Review by gonzalolanderos — APPROVED** [review]

**Comment by alvi1316** [comment]
@MgenGlder I think Registration is part of Auth Service. So, it would look consistent if we had the register function in `AuthServiceProvider.tsx` just like the login function and the react hook files are usually named `use<NameHere>.tsx`. For example, I think it should be named something like `useRegisterForm.tsx`.
